use std::fmt;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone)]
pub struct Lockfile {
    pub version: u32,
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub source: String,
}

#[derive(Debug)]
pub enum DepsError {
    IoError(std::io::Error),
    ParseError(String),
}

impl fmt::Display for DepsError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            DepsError::IoError(e) => write!(f, "I/O error reading lockfile: {}", e)?,
            DepsError::ParseError(msg) => write!(f, "Lockfile parse error: {}", msg)?,
        };
        Ok(())
    }
}

impl From<std::io::Error> for DepsError {
    fn from(e: std::io::Error) -> Self {
        DepsError::IoError(e)
    }
}

impl Default for Lockfile {
    fn default() -> Self {
        Self::new()
    }
}

impl Lockfile {
    pub fn new() -> Self {
        Self {
            version: 1,
            packages: Vec::new(),
        }
    }

    pub fn load_from_dir(dir: &Path) -> Result<Option<Self>, DepsError> {
        let lock_path = dir.join("ferrite.lock");
        if !lock_path.exists() {
            return Ok(None);
        }
        let content = fs::read_to_string(&lock_path)?;
        Ok(Some(Self::parse(&content)?))
    }

    fn parse(input: &str) -> Result<Self, DepsError> {
        let mut version = 1;
        let mut packages = Vec::new();
        let mut current_package = None;

        for raw_line in input.lines() {
            let line = raw_line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            if line == "[[package]]" {
                if let Some(pkg) = current_package.take() {
                    packages.push(pkg);
                }
                current_package = Some(LockedPackage {
                    name: String::new(),
                    version: String::new(),
                    source: String::new(),
                });
                continue;
            }

            if let Some((k, v)) = line.split_once('=') {
                let key = k.trim();
                let value = v.trim().trim_matches('"');
                if key == "version" && current_package.is_none() {
                    if let Ok(v) = value.parse::<u32>() {
                        version = v;
                    }
                } else if let Some(pkg) = current_package.as_mut() {
                    match key {
                        "name" => pkg.name = value.to_string(),
                        "version" => pkg.version = value.to_string(),
                        "source" => pkg.source = value.to_string(),
                        _ => {}
                    }
                }
            }
        }
        if let Some(pkg) = current_package {
            packages.push(pkg);
        }

        Ok(Self { version, packages })
    }

    pub fn save_to_dir(&self, dir: &Path) -> Result<(), DepsError> {
        let mut s = String::new();
        s.push_str("# This file is automatically generated by Ferrite.\n");
        s.push_str("# It is not intended for manual editing.\n");
        s.push_str(&format!("version = {}\n\n", self.version));

        for pkg in &self.packages {
            s.push_str("[[package]]\n");
            s.push_str(&format!("name = \"{}\"\n", pkg.name));
            s.push_str(&format!("version = \"{}\"\n", pkg.version));
            s.push_str(&format!("source = \"{}\"\n\n", pkg.source));
        }

        let lock_path = dir.join("ferrite.lock");
        fs::write(lock_path, s)?;
        Ok(())
    }
}

pub fn resolve_dependencies(manifest: &super::manifest::Manifest) -> Result<Lockfile, DepsError> {
    let mut lock = Lockfile::new();
    for (name, version_req) in &manifest.dependencies {
        lock.packages.push(LockedPackage {
            name: name.clone(),
            version: version_req.clone(),
            source: format!("registry+https://github.com/ferrite-lang/index#{}", name),
        });
    }
    Ok(lock)
}

pub fn add_dependency(dir: &Path, pkg_name: &str, version: &str) -> Result<(), DepsError> {
    let manifest_path = dir.join("ferrite.toml");
    if !manifest_path.exists() {
        return Err(DepsError::ParseError("ferrite.toml not found".to_string()));
    }
    let content = fs::read_to_string(&manifest_path)?;

    let dep_line = format!("{} =", pkg_name);
    if content
        .lines()
        .any(|line| line.trim().starts_with(&dep_line))
    {
        return Err(DepsError::ParseError(format!(
            "Dependency '{}' already exists",
            pkg_name
        )));
    }

    let mut lines: Vec<String> = content.lines().map(|s| s.to_string()).collect();
    let mut insert_idx = None;
    for (i, line) in lines.iter().enumerate() {
        if line.trim() == "[dependencies]" {
            insert_idx = Some(i + 1);
            break;
        }
    }

    let new_line = format!("{} = \"{}\"", pkg_name, version);
    if let Some(idx) = insert_idx {
        lines.insert(idx, new_line);
    } else {
        lines.push("[dependencies]".to_string());
        lines.push(new_line);
    }

    fs::write(&manifest_path, lines.join("\n") + "\n")?;
    Ok(())
}

pub fn remove_dependency(dir: &Path, pkg_name: &str) -> Result<(), DepsError> {
    let manifest_path = dir.join("ferrite.toml");
    if !manifest_path.exists() {
        return Err(DepsError::ParseError("ferrite.toml not found".to_string()));
    }
    let content = fs::read_to_string(&manifest_path)?;

    let dep_line = format!("{} =", pkg_name);
    let mut new_lines = Vec::new();
    let mut found = false;
    for line in content.lines() {
        if line.trim().starts_with(&dep_line) {
            found = true;
            continue;
        }
        new_lines.push(line);
    }

    if !found {
        return Err(DepsError::ParseError(format!(
            "Dependency '{}' not found",
            pkg_name
        )));
    }

    fs::write(&manifest_path, new_lines.join("\n") + "\n")?;
    Ok(())
}
